# Generated by Django 3.2.4 on 2021-06-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210605_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='landing_page_image',
            field=models.URLField(default='https://res.cloudinary.com/bernicecloud/image/upload/v1622907260/default_image_01_x3tuoe_vormsr.png'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(default='https://res.cloudinary.com/bernicecloud/image/upload/v1622906375/icons8-male-user-100_zratap_kygylf.png'),
        ),
    ]
